version: '3'

networks:
  develop:

volumes:
  db-data:

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - develop

  fpm:
    build:
      context: ./config/php/
      dockerfile: Dockerfile
    image: max/laravel
    restart: unless-stopped
    container_name: workspace
    working_dir: /var/www
    volumes:
      - ./workspace:/var/www
    networks:
      - develop

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./workspace:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - develop
    links:
      - fpm
